TOPLEVEL_LANG = verilog

VERILOG_SOURCES = \
    $(PWD)/../rtl/alu.sv \
    $(PWD)/../rtl/controlUnit.sv \
    $(PWD)/../rtl/topLevelTest.sv

TOPLEVEL = alu_control_test
MODULE = addStuff_tb

SIM = icarus

include $(shell cocotb-config --makefiles)/Makefile.sim